import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
  container:{
    flex:2,
    //backgroundColor:'black',
  },
  viewFname:{
    width:170,
    height:40,
    backgroundColor: '#fff', 
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },
  viewLname:{
    width:170,
    height:40,
    backgroundColor: '#fff',
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },
  viewMnumber:{
    width:360,
    height:40,
    backgroundColor: '#fff',
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },
  viewMale:{
    width:170,
    height:40,
    backgroundColor: '#fff',
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },
  viewFemale:{
    width:170,
    height:40,
    backgroundColor: '#fff',
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },
  viewPassword:{
    width:360,
    height:40,
    backgroundColor: '#fff',
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },
  ViewCPassword:{
    width:360,
    height:40,
    backgroundColor: '#fff',
    shadowColor: '#000000',
    shadowOffset:{ width:0, height:2 },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius:3,
    marginTop:'5%',
    paddingHorizontal :10,
  },

  loginButton:{
    width:400,
    height:40,
    backgroundColor: '#0073C0',
    //borderRadius:5,

  },
  loginTitle:{
    color: '#fff',
    textAlign:'center',
    //paddingLeft: 200,
    paddingTop: 8,
  }
    
  });

  export default styles
